name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Build and Deploy
        run: |
          npm install  # If you need to install dependencies
          npm run build  # Replace with your build command
          mv ./path-to-your-source-directory ./path-to-your-destination-directory
          echo 'Your GitHub Pages site has been built and moved.'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./path-to-your-destination-directory  # Specify the path to your source directory
